/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.Usuario;
import Model.Computador;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Karlos
 */
public class TelaPrincipal extends javax.swing.JFrame {
    Usuario user = new Usuario();
    Computador comp = new Computador();
    

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setIcon();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jokenpo_titulo = new javax.swing.JLabel();
        escolhaOpcao = new javax.swing.JLabel();
        textPedra = new javax.swing.JLabel();
        textPapel = new javax.swing.JLabel();
        textTesoura = new javax.swing.JLabel();
        iconPedra = new javax.swing.JLabel();
        iconPapel = new javax.swing.JLabel();
        iconTesoura = new javax.swing.JLabel();
        Log = new javax.swing.JTextField();
        Log1 = new javax.swing.JTextField();
        Log2 = new javax.swing.JTextField();
        botao_sobre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar4.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar5.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar5.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar6.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar6.add(jMenu10);

        jMenu11.setText("File");
        jMenuBar7.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar7.add(jMenu12);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jokenpo");
        setAlwaysOnTop(true);
        setIconImage(getIconImage());
        setResizable(false);

        jokenpo_titulo.setBackground(new java.awt.Color(102, 204, 255));
        jokenpo_titulo.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jokenpo_titulo.setForeground(new java.awt.Color(0, 0, 0));
        jokenpo_titulo.setText("JOKENPÔ");

        escolhaOpcao.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        escolhaOpcao.setText("ESCOLHA UMA OPÇÃO:");

        textPedra.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        textPedra.setText("Pedra");

        textPapel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        textPapel.setText("Papel");

        textTesoura.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        textTesoura.setText("Tesoura");

        iconPedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2730149_gem_harry_outline_philosophers_potter_icon.png"))); // NOI18N
        iconPedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconPedraMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconPedraMousePressed(evt);
            }
        });

        iconPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/622402_paper_documents_note_page_text_icon (1).png"))); // NOI18N
        iconPapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconPapelMousePressed(evt);
            }
        });

        iconTesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/326596_content_cut_scissors_icon (1).png"))); // NOI18N
        iconTesoura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconTesouraMousePressed(evt);
            }
        });

        Log.setEditable(false);
        Log.setBackground(new java.awt.Color(204, 204, 204));
        Log.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Log.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogActionPerformed(evt);
            }
        });

        Log1.setEditable(false);
        Log1.setBackground(new java.awt.Color(204, 204, 204));
        Log1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Log1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Log1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log1ActionPerformed(evt);
            }
        });

        Log2.setEditable(false);
        Log2.setBackground(new java.awt.Color(204, 204, 204));
        Log2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Log2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Log2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log2ActionPerformed(evt);
            }
        });

        botao_sobre.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        botao_sobre.setText("SOBRE");
        botao_sobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_sobreMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/326679_refresh_reload_icon (1).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iconPedra)
                                .addGap(18, 18, 18)
                                .addComponent(iconPapel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(textPedra)
                                .addGap(38, 38, 38)
                                .addComponent(textPapel)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(iconTesoura))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(textTesoura))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(escolhaOpcao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jokenpo_titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botao_sobre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Log1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Log, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Log2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botao_sobre)
                .addGap(11, 11, 11)
                .addComponent(jokenpo_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(escolhaOpcao)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPapel)
                    .addComponent(textPedra)
                    .addComponent(textTesoura))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconPedra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconTesoura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconPapel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(Log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Log1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Log2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iconPedraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPedraMouseClicked
        
    }//GEN-LAST:event_iconPedraMouseClicked

    private void iconPedraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPedraMousePressed
        user.setUsuario(1);
        Log.setText("Você escolheu: PEDRA");
        user.anuncioJogada();
        
        if(user.getUsuario()==1 || user.getUsuario() == 2 || user.getUsuario() == 3){
            comp.jogadaComputador();
            comp.getComputador();
            if(comp.getComputador()==1){
                Log1.setText("Computador escolheu: PEDRA");
            }else if(comp.getComputador()==2){
                Log1.setText("Computador escolheu: PAPEL");
            }else{
                Log1.setText("Computador escolheu: TESOURA");
            }
            comp.jokenpo();
        }else{
            JOptionPane.showMessageDialog(null, "Escolha uma opção válida", "Ops!", JOptionPane.ERROR_MESSAGE);
        }
        
        if(user.getUsuario()==comp.getComputador()){
            System.out.println("\nEmpate!");
            Log2.setText("Empate!");
            Log2.setBackground(Color.yellow);
        }else{
            if(user.getUsuario()==1 && comp.getComputador()==2 || user.getUsuario()==2 && comp.getComputador()==3 || user.getUsuario()==3 && comp.getComputador()==1) {
                System.out.println("\nVocê Perdeu!");
                Log2.setText("Você Perdeu!");
                Log2.setBackground(Color.red);
            }else{
                System.out.println("\nVocê Ganhou!");
                Log2.setText("Você Ganhou!");
                Log2.setBackground(Color.green);
            }
        }

        System.out.println("\n______________________");
    }//GEN-LAST:event_iconPedraMousePressed

    private void iconPapelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPapelMousePressed
        user.setUsuario(2);
        Log.setText("Você escolheu: PAPEL");
        user.anuncioJogada();
        
        if(user.getUsuario()==1 || user.getUsuario() == 2 || user.getUsuario() == 3){
            comp.jogadaComputador();
            comp.getComputador();
            if(comp.getComputador()==1){
                Log1.setText("Computador escolheu: PEDRA");
            }else if(comp.getComputador()==2){
                Log1.setText("Computador escolheu: PAPEL");
            }else{
                Log1.setText("Computador escolheu: TESOURA");
            }
            comp.jokenpo();
        }else{
            JOptionPane.showMessageDialog(null, "Escolha uma opção válida", "Ops!", JOptionPane.ERROR_MESSAGE);
        }
        
        if(user.getUsuario()==comp.getComputador()){
            System.out.println("\nEmpate!");
            Log2.setText("Empate!");
            Log2.setBackground(Color.yellow);
        }else{
            if(user.getUsuario()==1 && comp.getComputador()==2 || user.getUsuario()==2 && comp.getComputador()==3 || user.getUsuario()==3 && comp.getComputador()==1) {
                System.out.println("\nVocê Perdeu!");
                Log2.setText("Você Perdeu!");
                Log2.setBackground(Color.red);
            }else{
                System.out.println("\nVocê Ganhou!");
                Log2.setText("Você Ganhou!");
                Log2.setBackground(Color.green);
            }
        }

        System.out.println("\n______________________");
    }//GEN-LAST:event_iconPapelMousePressed

    private void iconTesouraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconTesouraMousePressed
        user.setUsuario(3);
        Log.setText("Você escolheu: TESOURA");
        user.anuncioJogada();
        
        if(user.getUsuario()==1 || user.getUsuario() == 2 || user.getUsuario() == 3){
            comp.jogadaComputador();
            comp.getComputador();
            if(comp.getComputador()==1){
                Log1.setText("Computador escolheu: PEDRA");
            }else if(comp.getComputador()==2){
                Log1.setText("Computador escolheu: PAPEL");
            }else{
                Log1.setText("Computador escolheu: TESOURA");
            }
            comp.jokenpo();
        }else{
            JOptionPane.showMessageDialog(null, "Escolha uma opção válida", "Ops!", JOptionPane.ERROR_MESSAGE);
        }
        
        if(user.getUsuario()==comp.getComputador()){
            System.out.println("\nEmpate!");
            Log2.setText("Empate!");
            Log2.setBackground(Color.yellow);
        }else{
            if(user.getUsuario()==1 && comp.getComputador()==2 || user.getUsuario()==2 && comp.getComputador()==3 || user.getUsuario()==3 && comp.getComputador()==1) {
                System.out.println("\nVocê Perdeu!");
                Log2.setText("Você Perdeu!");
                Log2.setBackground(Color.red);
            }else{
                System.out.println("\nVocê Ganhou!");
                Log2.setText("Você Ganhou!");
                Log2.setBackground(Color.green);
            }
        }

        System.out.println("\n______________________");
    }//GEN-LAST:event_iconTesouraMousePressed

    private void LogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogActionPerformed
        
    }//GEN-LAST:event_LogActionPerformed

    private void Log1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Log1ActionPerformed

    private void Log2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Log2ActionPerformed

    private void botao_sobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_sobreMouseClicked
        Sobre sbr = new Sobre();
        sbr.setVisible(true);
    }//GEN-LAST:event_botao_sobreMouseClicked

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        Log.setText("");
        Log1.setText("");
        Log2.setText("");
        Log2.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Log;
    private javax.swing.JTextField Log1;
    private javax.swing.JTextField Log2;
    private javax.swing.JLabel botao_sobre;
    private javax.swing.JLabel escolhaOpcao;
    private javax.swing.JLabel iconPapel;
    private javax.swing.JLabel iconPedra;
    private javax.swing.JLabel iconTesoura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JLabel jokenpo_titulo;
    private javax.swing.JLabel textPapel;
    private javax.swing.JLabel textPedra;
    private javax.swing.JLabel textTesoura;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("handIcon.png")));
    }

       
      
    
}